#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Google
  module Fonts
    # forward declarations
    class FamilyProto < ::ProtocolBuffers::Message; end
    class FontProto < ::ProtocolBuffers::Message; end
    class AxisSegmentProto < ::ProtocolBuffers::Message; end
    class SourceProto < ::ProtocolBuffers::Message; end

    class FamilyProto < ::ProtocolBuffers::Message
      # forward declarations
      class RegistryDefaultOverridesEntry < ::ProtocolBuffers::Message; end

      set_fully_qualified_name "google.fonts.FamilyProto"

      # nested messages
      class RegistryDefaultOverridesEntry < ::ProtocolBuffers::Message
        set_fully_qualified_name "google.fonts.FamilyProto.RegistryDefaultOverridesEntry"

        optional :string, :key, 1
        optional :float, :value, 2
      end

      required :string, :name, 1
      required :string, :designer, 2
      required :string, :license, 3
      required :string, :category, 4
      required :string, :date_added, 5
      repeated ::Google::Fonts::FontProto, :fonts, 6
      repeated :string, :aliases, 7
      repeated :string, :subsets, 8
      optional :string, :ttf_autohint_args, 9
      repeated ::Google::Fonts::AxisSegmentProto, :axes, 10
      repeated ::Google::Fonts::FamilyProto::RegistryDefaultOverridesEntry, :registry_default_overrides, 11
      optional ::Google::Fonts::SourceProto, :source, 12
    end

    class FontProto < ::ProtocolBuffers::Message
      set_fully_qualified_name "google.fonts.FontProto"

      required :string, :name, 1
      required :string, :style, 2
      required :int32, :weight, 3
      required :string, :filename, 4
      required :string, :post_script_name, 5
      required :string, :full_name, 6
      optional :string, :copyright, 7
    end

    class AxisSegmentProto < ::ProtocolBuffers::Message
      set_fully_qualified_name "google.fonts.AxisSegmentProto"

      optional :string, :tag, 1
      optional :float, :min_value, 2
      optional :float, :max_value, 4
    end

    class SourceProto < ::ProtocolBuffers::Message
      set_fully_qualified_name "google.fonts.SourceProto"

      optional :string, :repository_url, 1
      optional :string, :commit, 2
    end

  end
end
